services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/Users/jerem/Desktop/Développement Holberton/holbertonschool-softy-pinko-docker/task6/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - back-end
      - front-end

  front-end:
    image: nginx:latest
    volumes:
      - ./front-end:/usr/share/nginx/html

  back-end:
    build:
      context: ./back-end
    ports:
      - "5252"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
