services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: t5-back-end-image

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: t5-front-end-image
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: t5-proxy-image
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
